### ISSUE TITLE
Package versions have conflicting dependencies

### ISSUE THREAD

**Issue by happygirlzt** [jinfenglin/TraceBERT#1]
Hi there, I tried to install the required packages by the given requirements.txt. However, it seems that `transformers` and `tokenizers` versions have conflicts. Please confirm the versions. Thank you!
```
ERROR: Cannot install -r requirement.txt (line 76) and tokenizers==0.7.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested tokenizers==0.7.0
    transformers 2.8.0 depends on tokenizers==0.5.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by jinfenglin** [comment]
Thanks! I verified the issue exists when installing the packages in a new virtualenv. 
I guess huggingface updated dependencies constraints in their packages.
I will update the requirement file to fix it.
