### ISSUE TITLE
请问使用余弦相似度的效果如何？

### ISSUE THREAD

**Issue by zhuzhushiw** [jinfenglin/TraceBERT#9]
你好，lin，我在源码中看到你已经实现了使用余弦相似度的SBERT模型，但不知为何没有使用，是因为效果不太理想嘛？我用有监督的simCSE模型跑了一下，似乎MRR值不太理想，打扰了，谢谢。

**Comment by jinfenglin** [comment]
我在这篇文章中有做关于embedding相关的方法的比较。根据我实验的结果，用embedding+余弦相似度的方法模型对数据的拟合能力相对classification更弱。
https://arxiv.org/abs/2207.01084

**Comment by zhuzhushiw** [comment]
好的，谢谢
